// Repository facts reviewed on 2026-10-01. Descriptions refer to the source project;
// release availability is independently labeled and must not be inferred from main.
export const products = [
 {id:'lumenbox', name:'LumenBox', repo:'lumenbox', category:'work', mark:'box', color:'amber', license:'GPL-3.0', release:'v0.3.1', platform:'macOS', type:'download', featured:true,
  zh:{tag:'你的 AI 团队，有自己的电脑', description:'让多个 AI 智能体分工协作，在真实的 Linux 桌面上完成任务。过程看得见，你随时可以接手。', chips:['多智能体协作','可接管桌面','自带模型'], audience:'希望把真实工作交给 AI，同时保留过程与权限控制的个人和小团队。', steps:['选择模型服务，配置自己的 API key','连接本地容器或自己的 Linux 电脑','交给团队一个任务，查看桌面与执行记录'], readiness:'已有 macOS 安装包 · 早期版本', note:'需要模型服务与可用的 Linux 运行环境，例如本地 Docker。部分功能可能只在最新源码中提供；安装与首次启动要求以对应版本说明为准。', privacy:'智能体的记忆与工作文件由你的运行环境保存。使用云端模型或聊天平台时，相关内容会按你的配置发送给对应服务。'},
  en:{tag:'Your AI team. Their own computers.', description:'Give a team of AI agents real Linux desktops to get things done. Follow their work, inspect the record, and take over whenever you need.', chips:['Agent teams','Visible desktops','Your models'], audience:'Individuals and small teams who want to delegate real work while keeping control of the process and permissions.', steps:['Choose a model provider and bring your API key','Connect a local container or your Linux machine','Assign work, watch the desktops, and review the record'], readiness:'macOS installers · early release', note:'Requires a model service and a Linux runtime such as local Docker. Some features may exist only in current source. Check the selected release for installation and first-launch requirements.', privacy:'Memory and working files live in your chosen environment. Cloud models and chat integrations receive relevant content according to your configuration.'}},
 {id:'involute', name:'Involute', repo:'Involute', category:'work', mark:'orbit', color:'lilac', license:'Apache-2.0', platform:'Web · Docker', type:'invite',
  zh:{tag:'把协作，写成可验收的约定', description:'以契约、任务与验收为中心，让人和 AI 围绕明确的交付标准协作。', chips:['契约驱动','任务协作','明确验收'], audience:'需要把需求、执行与验收串起来的人与 AI 协作团队。', steps:['定义交付目标与验收条件','拆分任务，组织协作与执行','依据约定检查结果，留下可追溯记录'], readiness:'托管服务仅限邀请 · 支持自部署', note:'involute.lumenopen.com 仅向受邀用户开放，没有公开注册入口。项目提供 Docker / 源码自部署路径，暂无打包 Release。', privacy:'自部署的存储与访问范围由部署者配置；模型服务与外部集成的数据流需要单独检查。'},
  en:{tag:'Make the work clear. Make it verifiable.', description:'Organize human and AI collaboration around contracts, tasks, and explicit acceptance criteria.', chips:['Contract-driven','Shared tasks','Clear acceptance'], audience:'Teams that need a traceable path from intent to execution and acceptance.', steps:['Define the outcome and acceptance criteria','Break down the work and coordinate execution','Check the outcome against the agreement'], readiness:'Hosted access by invitation · self-hostable', note:'involute.lumenopen.com is invitation-only. There is no public signup. Docker and source-based self-hosting are available; no packaged releases are published.', privacy:'Storage and access depend on your deployment. Review model providers and external integrations separately.'}},
 {id:'planofplan', name:'Plan of Plan', repo:'planofplan', category:'work', mark:'plan', color:'green', license:null, platform:'Source', type:'source',
  zh:{tag:'看清编码工作的来龙去脉', description:'追踪 AI 编码会话、工作进展与成本，把分散的执行过程变成可回看的工作记录。', chips:['会话追踪','工作记录','成本可见'], audience:'同时使用 AI 编码工具，希望了解工作进展与消耗的开发者。', steps:['按照仓库文档从源码构建','连接支持的编码工作流','查看会话、工作记录与成本线索'], readiness:'源码构建 · 尚未声明许可证', note:'目前以源码构建为主，未发布安装包。仓库尚未声明开源许可证；使用、修改和分发前请先确认授权。', privacy:'编码会话可能包含敏感代码与路径。接入前请核对采集、存储和模型调用设置。'},
  en:{tag:'See the story behind the coding.', description:'Trace AI coding sessions, work progress, and cost. Turn scattered execution into a record you can revisit.', chips:['Session tracing','Work history','Cost visibility'], audience:'Developers who want a clearer view of work and usage across AI coding sessions.', steps:['Build from source using the repository guide','Connect a supported coding workflow','Review sessions, work history, and cost signals'], readiness:'Build from source · license not declared', note:'No installer is published. The repository has not declared an open-source license. Confirm permission before using, modifying, or distributing its code.', privacy:'Coding sessions can contain sensitive code and paths. Review collection, storage, and model settings before connecting them.'}},
 {id:'ovp2', name:'OVP2', repo:'obsidian_vault_pipeline', category:'knowledge', mark:'vault', color:'amber', license:'MIT / Apache-2.0', release:'desktop-v2.0.2', platform:'macOS', type:'download', featured:true,
  zh:{tag:'让知识，回到证据本身', description:'从材料与来源出发，沉淀可追溯的知识。为自己的知识库建立理解、整理与检索的工作流。', chips:['来源可追溯','知识沉淀','桌面工作流'], audience:'希望将持续收集的资料变成有依据、可检索知识的研究者与创作者。', steps:['引入资料与来源','整理内容，保留证据关系','在自己的知识工作流中查找与复用'], readiness:'macOS 桌面版本', note:'桌面版本为 desktop-v2.0.2。不同组件采用 MIT / Apache-2.0 许可证，具体范围请查看仓库中的许可文件。', privacy:'资料可能经过你配置的模型或处理服务。请检查具体工作流，避免把“本地知识库”理解成所有处理均离线。'},
  en:{tag:'Knowledge, with the evidence intact.', description:'Start with sources. Build a traceable knowledge workflow for understanding, organizing, and finding what matters.', chips:['Traceable sources','Lasting knowledge','Desktop workflow'], audience:'Researchers and creators who want collected material to become grounded, searchable knowledge.', steps:['Bring in materials and sources','Organize content while preserving evidence','Find and reuse it in your knowledge workflow'], readiness:'macOS desktop release', note:'Desktop release: desktop-v2.0.2. Components use MIT / Apache-2.0 licenses; see the repository license files for their scope.', privacy:'Materials may be processed by configured models or services. A local knowledge base does not mean every processing step is offline.'}},
 {id:'lumen-navi', name:'Lumen Navi', repo:'lumen-navi', category:'knowledge', mark:'navi', color:'blue', license:'GPL-3.0', release:'v0.1.0', platform:'macOS', type:'download',
  zh:{tag:'为当下的工作，找回上下文', description:'围绕本地活动建立上下文，帮助你重新找到正在进行的工作与相关线索。', chips:['本地活动','工作上下文','线索回溯'], audience:'经常在应用和任务之间切换，需要找回工作上下文的人。', steps:['阅读数据采集与权限说明','配置你愿意记录的本地活动','回看相关上下文与工作线索'], readiness:'macOS 安装包 · v0.1.0', note:'当前可下载资产为 macOS 版本。请先阅读活动记录所需的系统权限与数据范围，再启用相关功能。', privacy:'本地活动可能涉及屏幕内容和其他个人信息。只启用必要的采集权限，并核对存储与外部模型设置。'},
  en:{tag:'Find your way back into the work.', description:'Build context around local activity to reconnect with what you were doing and the details around it.', chips:['Local activity','Work context','Retrace your steps'], audience:'People who move between apps and tasks and need to recover their working context.', steps:['Read the collection and permissions guide','Choose which local activity to record','Revisit relevant context and work signals'], readiness:'macOS installer · v0.1.0', note:'Published download assets are for macOS. Review system permissions and data collection before enabling activity capture.', privacy:'Local activity can contain screen content and personal information. Enable only necessary permissions and review storage and external model settings.'}},
 {id:'lumen-learn', name:'Lumen Learn', repo:'lumen-learn', category:'knowledge', mark:'learn', color:'lilac', license:'MIT', platform:'Source', type:'source',
  zh:{tag:'让理解，发生在互动里', description:'探索由 AI 驱动的互动教学运行时，让讲解、提问与反馈围绕学习过程展开。', chips:['互动教学','AI 反馈','教学运行时'], audience:'探索 AI 互动教学的开发者、教育者与学习工具构建者。', steps:['阅读运行时与示例说明','从源码配置教学环境','用示例探索交互与反馈'], readiness:'源码 / 教学运行时 · 暂无安装包', note:'仓库中的课程示例为合成演示，不是已开放的真实课程目录。当前没有面向大众的课程注册入口或打包 Release。', privacy:'教学内容与学习输入可能发送给配置的模型服务。涉及学生信息时，请先检查部署与数据处理方式。'},
  en:{tag:'Understanding happens through interaction.', description:'Explore an AI-powered teaching runtime where explanations, questions, and feedback respond to the learning process.', chips:['Interactive teaching','AI feedback','Teaching runtime'], audience:'Developers, educators, and builders exploring AI-assisted interactive learning.', steps:['Read the runtime and example documentation','Configure the teaching environment from source','Explore interaction and feedback with examples'], readiness:'Source / teaching runtime · no installer', note:'Course examples are synthetic demonstrations, not a real public course catalog. There is no public course registration or packaged release.', privacy:'Teaching materials and learning inputs may be sent to configured models. Review deployment and data processing before using student information.'}},
 {id:'lumen-asr', name:'Lumen ASR', repo:'lumen-asr', category:'create', mark:'audio', color:'green', license:'GPL-3.0', release:'v0.3.1', platform:'macOS ARM · Windows x64', type:'pre',
  zh:{tag:'说出来，让思路不断线', description:'用语音输入与转写减少打字的打断，把自然表达带入日常工作。', chips:['语音输入','音频转写','多种识别路径'], audience:'偏爱语音表达、希望减少输入摩擦的写作者和日常电脑用户。', steps:['选择与你设备匹配的预发布安装包','配置识别引擎与所需权限','开始语音输入或转写'], readiness:'v0.3.1 预发布 · Mac ARM / Windows x64', note:'v0.3.1 标记为预发布，适合愿意测试和反馈的用户。当前安装资产覆盖 macOS ARM 与 Windows x64。', privacy:'不同识别引擎的数据路径不同。云端识别会向服务商传输音频；使用前请确认所选引擎与相关授权。'},
  en:{tag:'Speak freely. Keep your train of thought.', description:'Bring natural speech into everyday work with voice input and transcription that reduce the interruption of typing.', chips:['Voice input','Transcription','Engine choices'], audience:'Writers and everyday computer users who prefer speaking to typing.', steps:['Choose the prerelease for your device','Configure a recognition engine and permissions','Start voice input or transcription'], readiness:'v0.3.1 prerelease · Mac ARM / Windows x64', note:'v0.3.1 is marked prerelease and suits users comfortable testing and providing feedback. Published installers cover macOS ARM and Windows x64.', privacy:'Data paths vary by recognition engine. Cloud recognition sends audio to the provider. Check the selected engine and consent requirements before recording.'}},
 {id:'lumen-cut', name:'Lumen Cut', repo:'lumen-cut', category:'create', mark:'cut', color:'amber', license:'AGPL-3.0-or-later', release:'v0.3.1', platform:'macOS ARM', type:'download',
  zh:{tag:'像编辑文字一样，编辑声音与画面', description:'以转写文本为入口处理音视频，让内容编辑更贴近你想表达的意思。', chips:['文本驱动剪辑','音视频工作流','转写辅助'], audience:'希望用文字结构整理音视频内容的创作者。', steps:['导入需要处理的音视频','生成并检查转写内容','围绕文本组织编辑与导出'], readiness:'macOS ARM 安装包 · v0.3.1', note:'当前已发布安装资产仅覆盖 macOS ARM。Windows 的云端 ASR 支持不代表已有 Windows 安装包。', privacy:'音视频与转写内容可能进入所选识别服务。请查看项目文档并确认素材的处理权限。'},
  en:{tag:'Edit the words. Shape the story.', description:'Use transcripts as a starting point for audio and video editing, so the workflow stays close to what you want to say.', chips:['Transcript-led editing','Audio & video','Transcription support'], audience:'Creators who want to organize audio and video through the structure of words.', steps:['Import audio or video','Generate and review the transcript','Organize edits and export through the text'], readiness:'macOS ARM installer · v0.3.1', note:'Published installer assets cover macOS ARM only. Windows cloud ASR support does not mean a Windows installer is available.', privacy:'Media and transcripts may be sent to your chosen recognition provider. Check the documentation and your rights to process the material.'}},
 {id:'mreviewer', name:'mReviewer', repo:'mreviewer', category:'work', mark:'review', color:'blue', license:'MIT', release:'v0.1.13', platform:'macOS · Linux', type:'download',
  zh:{tag:'为每一次合并，多一个视角', description:'用多个模型审查 Pull Request 与 Merge Request，让不同视角一起帮助发现代码问题。', chips:['多模型审查','PR / MR','开发者工具'], audience:'希望给代码审查增加模型辅助视角的开发者与维护者。', steps:['获取适合平台的二进制文件','按照文档配置代码平台与模型','对 PR / MR 发起审查并人工复核'], readiness:'macOS / Linux 二进制 · v0.1.13', note:'已有 macOS 与 Linux 发布资产。模型结果是审查辅助，仍需要开发者判断与复核。', privacy:'审查会把相关代码发送给配置的模型服务。请确认代码仓库的保密要求、平台权限与模型数据政策。'},
  en:{tag:'Another perspective before you merge.', description:'Review pull requests and merge requests with multiple models, bringing different perspectives to potential code issues.', chips:['Multi-model review','PR / MR','Developer tooling'], audience:'Developers and maintainers who want model-assisted perspectives in their review process.', steps:['Download a binary for your platform','Configure code hosting and model providers','Run a PR / MR review and verify the findings'], readiness:'macOS / Linux binaries · v0.1.13', note:'Published assets are available for macOS and Linux. Model findings are review assistance and still require developer judgment.', privacy:'Relevant code is sent to configured models. Check repository confidentiality, platform permissions, and provider data policies.'}}
];
export const categories={zh:{all:'全部产品',work:'AI 工作与开发',knowledge:'知识与学习',create:'声音与创作'},en:{all:'All products',work:'AI work & development',knowledge:'Knowledge & learning',create:'Voice & creation'}};
